repos:
-   repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: 'v1.5.7'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: autopep8